# Contextualização

<div style="text-align: justify"> 
A história de colonização e regularização de posses pode ser dividida em alguns períodos: o regime sesmaria (1500 a 1822), regime de posse (1824 a 1850), regime de Lei de Terras (1850 a 1889) e, por fim, o período republicano de 1899 que se perdura até os dias atuais.   

Os primeiros habitantes da Amazônia foram os índios que se relacionavam de forma harmônica. A partir do século 18 encontramos uma Amazônia composta, por indivíduos miscigenados (índios, brancos e negros). Deste modo, com a colonização portuguesa a agricultura e a pecuária passam a ter papel fundamental na região.   

Ainda na década de 60, as políticas de integração trazem uma nova aparência do colonialismo, tendo em vista que “a colonização sempre foi uma questão de Estado enquanto estratégia oficial de povoamento de novas terras, de ordenamento territorial” (CASTRO,2010 p. 108). Com o lema “Integrar para não entregar”, obras de infraestrutura foram realizadas na Amazônia com a intenção de integrar a região com o restante do país.   

Na década seguinte, diversas políticas públicas de ocupação refletiram diretamente no aumento do contingente populacional da região com incentivos a vários grupos sociais a se deslocarem até a Amazônia, principalmente camponeses, empresários e fazendeiros. Os chamados projetos de colonização e fundiários levaram a Amazônia atingir sete milhões de habitantes na década de 70. Nos anos 80, ainda que em menor escala, processos de migração continuaram a ser realizados, com famílias vindo das mais diferentes regiões do país.  

Vale ressaltar que, a partir dos anos 70, a ocupação da Amazônia tornou-se prioridade nacional e o governo federal passou a viabilizar e subsidiar a ocupação de terras para expansão pioneira. As políticas de ocupação procuraram aliar os empreendimentos de exploração econômica com estratégias geopolíticas (COSTA, 1997).  

Neste aspecto, em 1976 o governo regulariza a primeira terra na Amazônia. Uma medida provisória que à época permitiu a regularização de propriedades de até 60 mil hectares que tivessem sido adquiridos de “boa fé”. 
 
Essas políticas públicas apoiadas pelo governo federal sejam eles de colonização ou mesmo fundiários, foram executados em terras públicas federais, onde as famílias beneficiárias recebiam uma parcela de terras definidas pelo Incra ou outros grupos específicos como o Grupo Executivo de Terras do Araguaia e Tocantins – GETAT que atuou nos estados do Pará, Goiás (hoje Tocantins) e Maranhão com o objetivo de promover e executar as medidas de regularização fundiária e resolver os problemas de conflitos de terra. Esse órgão estatal também era responsável por articular o domínio do território do sul e sudeste do Pará. 

A criação de projetos em imóveis públicos passa de uma iniciativa do governo para um crescimento desordenado de ocupação de terras públicas, uma vez que grande número de ocupantes sem documentos de propriedade, que foi ou deveria ter sido resolvido com ações de titulação, sejam elas definitivas ou através de contratos como os Contratos de Alienação de Terras Públicas – CATPs ou os Contratos de Promessa de Compra e Venda – CPCVs. Esses títulos deveriam fechar um ciclo no qual os ocupantes de terras públicas receberiam seus títulos, cumpririam com as condições resolutivas descritas e teriam seu imóvel registrado no cartório de registro de imóveis, tendo assim finalizado o processo de transferência do imóvel público para o particular, transformando o ocupante em proprietário da parcela.  

Ademais, um dos primeiros marcos foi o 1º Programa Nacional de Reforma Agrária – I PNRA, criado em 10 de outubro de 1985, colocando a Reforma Agrária como ação prioritária da instituição. É importante destacar que todos os projetos criados antes, embora denominados projetos de assentamento, tinham uma característica associada a colonização e povoação. Ou seja, tinham uma característica mais próxima da regularização do que o projeto de assentamento.    

Na definição do INCRA, projeto de assentamento é um agrupamento de ações em determinada área, inclusive implantação de sistemas de produção sustentáveis. Por esta razão, o INCRA tem responsabilidade pela extensão rural, por concessão de créditos e por apoio aos assentados enquanto não houver emancipação do assentamento.   

Neste sentido, com base na Instrução Normativa nº 104 de 29 de janeiro de 2021, as áreas remanescentes de projetos de assentamento com características de colonização compreendem áreas ainda não tituladas, áreas não destinadas e tituladas pendentes da verificação das condições resolutivas, observado o disposto nas cláusulas contratuais do título expedido sobre a área. 

Vale evidenciar que as ocupantes irregulares dos projetos de colonização e de assentamento anteriores ao I PRNA (10/10/1985) passam a ser tratados como público de regularização fundiária, permitindo a regularização de áreas com situações que não eram admitidas, bem como não eram tratados como público de reforma agrária. 

Outros fatos de grande relevância também ocorreram neste percurso, dentre eles, a criação do Ministério de Desenvolvimento Agrário – MDA em 1999 e transformado na Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agrário (SEAD) em 2017, órgão ao qual o INCRA era vinculado, que à época instituiu a Secretaria de Reordenamento Agrário – SRA, sendo uma de suas ações a titulação de terras estaduais mediante convênio com os Estados, ação que o INCRA também fazia e ainda executa.   

Além disto, em 2009, há a criação do programa Terra Legal com a jurisdição nos 9 estados que compõem a “Amazônia Legal”, com o INCRA participando subsidiariamente nas ações de regularização fundiária, mas a condução do programa estava sob tutela da Secretaria Extraordinária de Regularização Fundiária na Amazônia Legal – Serfal, abrigada no MDA. É importante registrar que no decorrer destes oito anos sua ação foi bastante eficaz resultando emissão de cerca de 30 mil títulos, cadastramento de mais 140 mil áreas, georreferenciamento de 50 milhões de hectares e mais de 400 concessões de áreas para municípios que perderam a vocação agrícola e consequente formação de núcleos urbanos em municípios.  

Sendo assim, com a criação do Programa Terra Legal, o INCRA permaneceu com a responsabilidade de regularizar suas áreas e as da União nos demais estados da federação – 17 Estados, e no Distrito Federal. Em 2014 e 2015 com a extinção do programa Terra Legal, o INCRA retomou a execução do processo de regularização fundiária na Amazônia Legal, com ênfase nas regularizações das áreas remanescentes, renegociação de títulos vencidos e doação de núcleos urbanos para municípios, a partir das alterações ocorridas na Lei 11.952/2009, promovidas pela MP 759/2016, que foi convertida na Lei 13.465/17, passa-se a ter uma lei específica para a regularização fundiária de áreas do INCRA.  

A nova estrutura regimental do INCRA, aprovada pelo Decreto n.º 10.252, de 20 de fevereiro de 2020, em seu Art. 13, inciso II, alínea b, atribui a Diretoria de Governança Fundiária, a competência para executar as políticas de regularização fundiária e regularização das ocupações incidentes em terras de domínio da União com destinação agrária, no âmbito da Amazônia Legal, nos termos do disposto na Lei nº 11.952, de 25 de junho de 2009. Portanto, a atribuição legal de regularização Fundiária na Amazônia Legal, atualmente encontra-se sob responsabilidade do INCRA e, diretamente ligado à esta Diretoria de Governança Fundiária.  

Em se tratando de um contexto sobre arrecadação de terras devolutas, podemos conceituar como inalienáveis, indisponíveis e imprescritíveis. Uma vez identificadas, dependendo de sua localização, devem ser incorporadas ao patrimônio do respectivo ente federativo, passando a compor o universo de bens públicos dominicais. Ou seja, são aquelas que pertencem ao domínio público e que não se encontram afetas a uma utilização pública. Quando localizadas em áreas “indispensáveis à defesa das fronteiras, das fortificações e construções militares, das vias federais de comunicação e a preservação ambiental, definidas em Lei” (art. 20, Inciso II, Constituição de 1988) são consideradas bens da União. Residualmente, as demais são bens dos estados.  

A lei que disciplina a incorporação das terras devolutas ao patrimônio imobiliário da União é a Lei 6.383/76, que disciplina o processo discriminatório de terras devolutas. É nesta Lei que se encontra a atribuição do INCRA de representante da União para promover a discriminatória e a arrecadação das terras devolutas federais.  

Outrossim, a regularização fundiária consiste no conjunto de medidas jurídicas, ambientais e sociais com o objetivo de legalizar as ocupações e titular as terras da União ou do INCRA conforme legislação vigente. Realizando a regularização, o proprietário tem garantido seu direito de propriedade ao invés de uma situação precária de ocupação.    
O processo de regularização fundiária envolve as etapas de medição, demarcação e georreferenciamento da ocupação, cadastramento dos ocupantes no Sistema Nacional de Cadastro Rural, a titulação e o registro. É a partir da titulação que o poder público reconhece a legitimidade da ocupação e promove a alienação da terra ao particular.  

Por todo arrazoado, é importante destacar a importância das ações feitas pelo INCRA que em meados de 2019 até o presente momento, vem desenvolvendo uma gestão com a missão de implementar a política de regularização fundiária e contribuir para um desenvolvimento rural sustentável. 
 
Vale destacar uma parceria firmada entre INCRA/UNB que é resultado de uma das ações de grande importância para regularização fundiária. A experiência com o projeto Mais Amazônia que chega a um universo de mais de 20 mil análises de requerimento de regularização fundiária dentro da Amazônia Legal vem trazendo um norte para a cooperação, identificando os requerimentos, traçando o perfil dos demandantes e as condições para deferimento e indeferimento, mapeando e analisando as áreas possíveis de atuação.  

Com a quantidade dos requerimentos já analisados, podemos identificar a falta de alguns documentos necessários para o prosseguimento da análise de regularização fundiária, como por exemplo: falta de georreferenciamento, falta de documentação pessoal, bem como, verificamos muita área já destinada que não tem as suas condições analisadas, área que chegou a ser titulada e o próprio requerente pede cancelamento por falta de esclarecimento legal.  

Neste sentindo, não ter um acervo para dentro da Amazônia Legal condensado em um único ambiente, ou seja, ter isso de forma difusa e sem controle algum prejudica o processo de análise, uma vez que tentamos analisar um processo em que não se sabe se em algum momento aquela área já foi titulada. Com resultado disso, o INCRA começa a emitir vários documentos titulatórios gerando uma desordem e uma insegurança jurídica dentro do instituto.  

Diante do acima exposto, o INCRA, buscará em conjunto com a Universidade de Brasília – UnB campus Planaltina, através de termo de execução descentralizada avançar com a pesquisa que é a investigação a partir de banco de dados oficiais e livros fundiários de antigas ações de titulação em cada Superintendência Regional, elaborando e sistematizando os dados de parcelas rurais e urbanas localizadas em imóveis do INCRA dentro da Amazônia Legal.   

Assim, surge a importância e a necessidade do trabalho que executará a partir desse momento, onde o presente manual pretende regulamentar.
