# Cadastro Nacional de Florestas Públicas (CNFP)

<div style="text-align: justify">

O Cadastro Nacional de Florestas Públicas (CNFP) é um instrumento de planejamento da gestão florestal, que reúne dados georreferenciados sobre as florestas públicas brasileiras, de modo a oferecer aos gestores públicos e à população em geral uma base confiável de mapas, imagens e dados com informações relevantes para a gestão florestal. Os dados do CNFP auxiliam os processos de destinação das florestas públicas para uso comunitário, criação de unidades de conservação e realização de concessões florestais. O Cadastro contribui para a transparência, a participação social e unificação das informações sobre as florestas públicas.

O CNFP é formado pelo Cadastro de Florestas Públicas da União, pelos Cadastros de Florestas Públicas dos estados, Distrito Federal e municípios e está em processo de interligação ao Sistema Nacional de Cadastro Rural (SNCR) do Instituto Nacional de Colonização e Reforma Agrária (INCRA).

O cadastramento das florestas públicas segue três etapas:

- Identificação - mapeamento das florestas localizadas em áreas públicas;
- Delimitação- averbação (registro) do perímetro da floresta junto à matricula do imóvel público;
- Demarcação - implantação de marcos topográficos e colocação de placas informativas no campo.

Existem três tipos de florestas públicas federais:

- Florestas Públicas do TIPO A (FPA) - São florestas que apresentam destinação e dominialidade específica como as Unidades de Conservação da Natureza, as Terras Indígenas, os Assentamentos Rurais Públicos, as áreas militares e outras formas de destinação previstas em lei. São destinadas à proteção e conservação do meio ambiente e uso de comunidades tradicionais
- Florestas Públicas do TIPO B (FPB) - São as florestas localizadas em áreas arrecadadas pelo Poder Público, mas que ainda não foram destinadas.
- Florestas Públicas do TIPO C (FPC) - São as florestas localizadas em áreas de dominialidade indefinida, comumente chamadas de terras devolutas.

fonte: [Serviço Florestal Brasileiro](https://www.gov.br/agricultura/pt-br/assuntos/servico-florestal-brasileiro/cadastro-nacional-de-florestas-publicas){target="_blank"}

Os dados baixados do sítio do Seviço Florestral Brasileiro serão analisados abaixo para os polígonos dentro da área de estudo, amazônia legal e Maranhão, confrontando suas interações com as glebas federais de regularização fundiária administradas pelo Instituto Nacional de Colonização e Reforma Agrária - INCRA.

## Quantificação das florestas publicas por tipo

```{python}
#| echo: false

import geopandas as gpd
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap, ListedColormap
from IPython.display import display, Markdown
pd.options.display.float_format = '{:.4f}'.format
pd.set_option('display.precision', 4)
import warnings
warnings.filterwarnings('ignore')
glebas = gpd.read_file('../glebas-federais.gpkg', layer='glebas-mais-amazonia')
area_estudo = gpd.read_file('../glebas-federais.gpkg', layer='area-estudo')
uf = gpd.read_file('../glebas-federais.gpkg', layer='uf-brasil')
floresta=gpd.read_file('../glebas-federais.gpkg', layer='florestas-publicas', mask=area_estudo)
```

```{python}
#| echo: false
#| fig-align: center

fig, ax = plt.subplots()
floresta[floresta['area-estudo']==1].plot(ax=ax,alpha=0.5, column='tipo', legend=True,cmap = ListedColormap(["lawngreen", "lightseagreen"]),legend_kwds={'loc': 'lower center', 'bbox_to_anchor':(1.1,0.5)})
area_estudo.plot(ax=ax,facecolor="none", edgecolor="black")
uf[uf['amaz_legal']==1].plot(ax=ax,facecolor="none", edgecolor="grey")
plt.grid(visible=True)
plt.xlabel('Longitude (°)')
plt.ylabel('Latitude (°)')
plt.show()
```


```{python}
#| echo: false
#| fig-align: center

floresta_tipo = floresta.groupby('tipo').agg({'area_ha':'sum'})
floresta_tipo.reset_index(inplace=True)
floresta_tipo.rename(columns={
  'tipo':'Tipo de Floresta Publica',
  'area_ha': 'Área (ha)'
}).to_html(index=False)

```

A denominação de florestas publicas parece abranger integralmentes as poligonais já classificadas em outras atividades tais como áreas de assentamentos federais, assim, a denominação que pode remeter a uma área de vegetação nativa não é a realizada das poligonais existentes na base de dados.

As áreas mensuradas como florestas publicas abrangem divérsos uso do solo distintos de vegetação nativa, levando à conclusões equivocadas quando do uso da totalização de área.

Seguindo a definição do Serviço Florestal Brasileiro, as florestas publicas do *Tipo A - lorestas que apresentam destinação e dominialidade específica*, somariam 235.982.649 de hectares e as do *Tipo B - São as florestas localizadas em áreas arrecadadas pelo Poder Público, mas que ainda não foram destinadas* somariam 62.989.475 hectares. Porém esse número não corresponde à área ocupada por vergetação nativa nos respectivos polígonos.

## Florestas Públicas Não Destinadas por Unidade da Federação

A seguir iremos totalizar as floresta publicas não destinadas (Tipo B) por unidade da federação.

```{python}
#| echo: false

floresta_b = floresta[floresta['tipo']=='TIPO B']
fig_b, ax_b = plt.subplots()
floresta_b.plot(ax=ax_b,legend_kwds={'loc': 'lower center', 'bbox_to_anchor':(1.1,0.5)})
area_estudo.plot(ax=ax_b,facecolor="none", edgecolor="black")
uf[uf['amaz_legal']==1].plot(ax=ax_b,facecolor="none", edgecolor="grey")
plt.grid(visible=True)
plt.xlabel('Longitude (°)')
plt.ylabel('Latitude (°)')
plt.show()

display(Markdown('### Área Total de Florestas Públicas Não destinadas por Estado'))
floresta_b_area = floresta.groupby('uf').agg({'area_ha':'sum'})
floresta_b_area.reset_index(inplace=True)
floresta_b_area.rename(columns={
  'uf':'UF',
  'area_ha': 'Área (ha)'
}).sort_values('Área (ha)', ascending=False).to_html(index=False)
```

## Análise de sobreposição das Florestas Públicas e das Glebas Federais.

As florstas publicas não destinadas merecem uma maior atenção para que possa-se determinar a interação entre elas e as glebas federais adminstradas pelo INCRA, o que, em tese, determinaria uma destinação.

```{python}
#| echo: false
floresta_gleba = floresta_b.overlay(glebas, how='intersection')
```

```{python}
#| echo: false


fig_fp_gl, ax_fp_gl = plt.subplots()
floresta_gleba.plot(ax=ax_fp_gl)
uf[uf['amaz_legal']==1].plot(ax=ax_fp_gl,facecolor="none", edgecolor="grey")
plt.grid(visible=True)
plt.xlabel('Longitude (°)')
plt.ylabel('Latitude (°)')
plt.show()
floresta_gleba['Área Sobreposta (ha)'] = (floresta_gleba.to_crs(5880).area)/10000
floresta_b_area_sobreposta = floresta_gleba.groupby('uf_1').agg({'Área Sobreposta (ha)':'sum'})
display(Markdown('### Área de Florestas Públicas Não destinadas sobrepostas a Glebas Federais por Estado'))
floresta_b_area_sobreposta.reset_index(inplace=True)
floresta_b_area_sobreposta.rename(columns={
  'uf_1':'UF'
}).sort_values('Área Sobreposta (ha)', ascending=False).to_html(index=False)
```

### Análise das sobreposições

Apesar do estado com maior área de floresta publica não destinada ser o Amazonas, inclusive as que se sobrepõem às glebas federais administradas pelo INCRA, Rondônia e Tocantins possuem, percentualmente, maiores valores de sobreposição com 24,07% e 20,82% respectivamente, sendo Roraima o estado com menor percentual de sobreposição com apenas 0,22% das glebas federais dentro inteseccionando florestas públicas não destinadas.

UF|Área (ha)|Área Sobreposta (ha)|Percentual
:---:|---:|---:|---:|
RO|12.628.472,0000|3.039.903,7726|24,07%
TO|4.995.508,0000|1.040.161,5098|20,82%
PA|81.745.810,0000|7.044.767,9311|8,62%
MT|19.146.575,0000|1.526.235,2604|7,97%
AM|134.302.021,0000|8.929.946,6138|6,65%
AP|12.043.765,0000|676.060,5160|5,61%
MA|4.848.309,0000|257.863,7752|5,32%
AC|10.794.257,0000|250.900,7200|2,32%
RR|18.076.209,0000|39.950,8779|0,22%

</div>