
# Registros em Cartório



```{python}
#| echo: false
# Bibliotecas
import geopandas as gpd
import pandas as pd
import polars as pl
import numpy as np
import os
import matplotlib.pyplot as plt
from IPython.display import display, Markdown
pd.options.display.float_format = '{:.4f}'.format
pd.set_option('display.precision', 4)
```

```{python}
#| echo: false
glebas = gpd.read_file('../drive/Shapes Bases de Glebas e Projetos data 01.03.23/tab_glebas_federais.shp')
area_estudo = gpd.read_file('../drive/shapes_transformados/amazonia-legal-com-maranhao.shp')
uf = gpd.read_file('../drive/uf.shp')
```

<div style="text-align: justify">

A Lei 6.015 que dispõe sobre os registros públicos, e dá outras providências, estabelece que:


> Art. 172 - No Registro de Imóveis serão feitos, nos termos desta Lei, o registro e a averbação dos títulos ou atos constitutivos, declaratórios, translativos e extintos de direitos reais sobre imóveis reconhecidos em lei, " inter vivos" ou " mortis causa" quer para sua constituição, transferência e extinção, quer para sua validade em relação a terceiros, quer para a sua disponibilidade.
>
> Art. 176 - O Livro nº 2 - Registro Geral - será destinado, à matrícula dos imóveis e ao registro ou averbação dos atos relacionados no art. 167 e não atribuídos ao Livro nº 3.
>
>   § 1º A escrituração do Livro nº 2 obedecerá às seguintes normas:
>
>   I - cada imóvel terá matrícula própria, que será aberta por ocasião do primeiro ato de registro ou de averbação caso a transcrição possua todos os requisitos elencados para a abertura de matrícula;
>   
>   II - são requisitos da matrícula:
>
>   1) o número de ordem, que seguirá ao infinito;
>   2) a data;
>   3) a identificação do imóvel, que será feita com indicação:
>       a - se rural, do código do imóvel, dos dados constantes do CCIR, da denominação e de suas características, confrontações, localização e área;
>       b - se urbano, de suas características e confrontações, localização, área, logradouro, número e de sua designação cadastral, se houver.
>   
>   4) o nome, domicílio e nacionalidade do proprietário, bem como:
>       a) tratando-se de pessoa física, o estado civil, a profissão, o número de inscrição no Cadastro de Pessoas Físicas do Ministério da Fazenda ou do Registro Geral da cédula de identidade, ou à falta deste, sua filiação;
>       b) tratando-se de pessoa jurídica, a sede social e o número de inscrição no Cadastro Geral de Contribuintes do Ministério da Fazenda;
>   
>   5) o número do registro anterior;
>   
>   6) tratando-se de imóvel em regime de multipropriedade, a indicação da existência de matrículas, nos termos do § 10 deste artigo;
>   
>   III - são requisitos do registro no Livro nº 2:
>   
>   1) a data;
>   
>   2) o nome, domicílio e nacionalidade do transmitente, ou do devedor, e do adquirente, ou credor, bem como:
>       a) tratando-se de pessoa física, o estado civil, a profissão e o número de inscrição no Cadastro de Pessoas Físicas do Ministério da Fazenda ou do Registro Geral da cédula de identidade, ou, à falta deste, sua filiação;
>       b) tratando-se de pessoa jurídica, a sede social e o número de inscrição no Cadastro Geral de Contribuintes do Ministério da Fazenda;
>   
>   3) o título da transmissão ou do ônus;
>   
>   4) a forma do título, sua procedência e caracterização;
>   
>   5) o valor do contrato, da coisa ou da dívida, prazo desta, condições e mais especificações, inclusive os juros, se houver.

---

**Definição de Código Nacional de Serventias (CNS).**

_CNS_: é o Código do Cartório de Registro de Imóveis em que o imóvel vizinho tem registro, este CNS – Código Nacional de Serventias.

---

## Chave de identificação registral dos imóveis.

Conforme descrito acima, a identificação registral de um imóvel é composta por uma chave dupla sendo o número da matrícula (qua vai de 1 ao infinito) e o Código Nacional de Serventias - CNS que identifica o cartório no qual a matrícula foi registrada. Assim, na tabela de informações sobre as gelbas, duas colunas são necessárias para identificação registral da gleba.

_**Matrícula:**_ receberá o número da matrícula, R ou AV, livro e página;

_**CNS:**_ receberá o número correspondente ao Código Nacional de Serventias do cartório de registro da matrícula.


## Análise das informações

:::{.table-center}
```{python}
#| echo: false
glebas_matricula = glebas[['uf','matricula','cartorio']].copy()
glebas_matricula['total']=1
display(Markdown('### Número de glebas com informações de matrícula e CNS do Catório cadastradas.'))
uf_mat = glebas_matricula['uf'].unique()

tot_glebas = glebas_matricula.groupby('uf').agg({
    'total':'sum',
    'matricula':'count',
    'cartorio':'count'
})

tot_glebas['sem-matricula'] = glebas_matricula[glebas_matricula['matricula'].isnull()].groupby('uf').count()['total']

tot_glebas.rename(columns={
    'total':'Total de Áreas',
    'matricula': 'Matrículas Cadastradas',
    'cartorio': 'Matrículas com CNS',
    'sem-matricula': 'Matrículas Sem Cadastro'}).to_html(index=False)

```
:::
