project:
  type: book
  output-dir: docs

jupyter: python3

book:
  sidebar:
    search: false
  title: "Análise Geográfica das Glebas Federais"
  author: "+ Amazônia"
  date: "03/10/2023"
  repo-url: https://maisamazoniageo.github.io/book/
  cover-image: img/mais_amazonia.png
  chapters:
    - index.qmd
    - 1-contexto.qmd
    - 2-objetivos.qmd
    - 3-metodologia.qmd
    - 4-variaveis.qmd
    - 5-delimitacao.qmd
    - 6-info.qmd
    - 7-ctrf.qmd
    - 8-matricula.qmd
    - 9-sr.qmd
    - 10-situacao.qmd
    - 11-assentimento.qmd
    - 12-sncr.qmd
    - 13-terra-indigena.qmd
    - 14-unidade-conservacao.qmd
    - 15-acre.qmd
    - 16-amapa.qmd
    - 17-amazonas.qmd
    - 18-maranhao.qmd
    - 19-matogrosso.qmd
    - 20-para.qmd
    - 21-rondonia.qmd
    - 22-roraima.qmd
    - 23-tocantins.qmd
    - 24-analise-individual-acre.qmd
    - 25-analise-individual-amapa.qmd
    - 26-analise-individual-amazonas.qmd
    - 27-analise-individual-maranhao.qmd
    - 28-analise-individual-matogrosso.qmd
    - 29-analise-individual-para.qmd
    - 30-analise-individual-rondonia.qmd
    - 31-analise-individual-roraima.qmd
    - 32-analise-individual-tocantins.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    default-image-extension: png
    page-layout: full
    css: styles.css
    toc: false
    fig-width: 9
    fig-height: 6.5
    fig-align: center

  pdf:
    documentclass: report
    default-image-extension: tex
    margin-left: 30mm
    margin-right: 20mm
    margin-top: 20mm
    margin-bottom: 20mm
    toc: true
    number-sections: true
    number-depth: 3

lenguage:
  leng: pt

plugins:
  - mkquartodocs
