# References {.unnumbered}

::: {#refs}
:::

## Banco de dados espacial - geopackage

As camadas utilizadas estão compiladas em um bando de dados espacial geopackage. A especificação GeoPackage descreve um conjunto de convenções para armazenamento de dados espaciais dentro de um banco de dados SQLite: Podem compor um gpkg: Vetores, Tiles, arquivos raster e matrizes em várias escalas.

|Nome da Tabela                   |Geometria      |EPSG              |descrição|
|--------------                   |---------      |----              |---------|
|amazonia-legal                   |MULTIPOLYGON   |SIRGAS 2000 (4674)| 
|area-estudo                      |MULTIPOLYGON   |SIRGAS 2000 (4674)| 
|faixa-fronteira-150km            |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|florestas-publicas               |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|gleba-centroid-hub_sr            |MULTILINESTRING|SIRGAS 2000 (4674)|
|glebas-centroid                  |POINT          |SIRGAS 2000 (4674)|
|glebas-centroid-hub-menos-dist-sr|MULTILINESTRING|SIRGAS 2000 (4674)|
|glebas-centroid-menor-dist-sr    |POINT          |SIRGAS 2000 (4674)|
|glebas-mais-amazonia             |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|municipios-area-estudo           |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|sr_incra                         |POINT          |SIRGAS 2000 (4674)|
|ti-geral                         |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|ti-geral-pts                     |POINT          |SIRGAS 2000 (4674)|
|ti-portarias                     |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|ti-portarias-pts                 |POINT          |SIRGAS 2000 (4674)|
|uc                               |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|uf-brasil                        |MULTIPOLYGON   |SIRGAS 2000 (4674)|
|sigef-geral                      |MULTIPOLYGON   |SIRGAS 2000 (4674)|


## Fontes de Dados

### Unidades da Federação
link: *[estados](https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2022/Brasil/BR/BR_UF_2022.zip)*

### Limites Municipais
link: *[limites municipais](https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2022/Brasil/BR/BR_Municipios_2022.zip)*

### Faixa de Fronteira
link: *[fronteira](https://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/municipios_da_faixa_de_fronteira/2022/Faixa_de_Fronteira_por_UF_2022_shp.zip)*

### Florestas Públicas
link: *[florestas](https://mmabr-my.sharepoint.com/:u:/g/personal/10810147769_mma_gov_br/EdkDvfzdlpJAneLK56geXAUBq-Pu8pCB5FTrLrD4WOUqnA?e=2fK6JC)*

### Terras Indígenas
link: *[terra indígena](https://geoserver.funai.gov.br/geoserver/Funai/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=Funai%3Atis_poligonais_portarias&maxFeatures=10000&outputFormat=application%2Fvnd.google-earth.kml%2Bxml)*

### Unidades de Conservação
link: *[unidade de conservação](https://dados.gov.br/dados/conjuntos-dados/unidadesdeconservacao)*

### Território Quilombola
link: *[quilombos](https://acervofundiario.incra.gov.br/)*

### Projetos de Assentamentos
link: *[assentamentos](https://acervofundiario.incra.gov.br/)*

### Imóveis particulares certificados no SIGEF
Banco de dados *CARTOS*, acesso restrito INCRA

### Imóveis particulares certificados no SNCI
Banco de dados *CARTOS*, acesso restrito INCRA

